// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'I:phsliders': typeof import('~icons/ph/sliders')['default']
    'ICarbon:arrowDown': typeof import('~icons/carbon/arrow-down')['default']
    IEmojioneV1FlagForChina: typeof import('~icons/emojione-v1/flag-for-china')['default']
    IPhTranslateBold: typeof import('~icons/ph/translate-bold')['default']
    ITwemojiFlagUsOutlyingIslands: typeof import('~icons/twemoji/flag-us-outlying-islands')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
